# Generated by Django 5.0.3 on 2024-03-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsmodel',
            name='auto_park',
        ),
    ]
